name: ble_peripheral_windows
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9
  python_channel: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: BlePeripheralWindowsPluginCApi
